// Copyright 2026 the Hird Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

//! Seeded, byte-deterministic corpus generators: one program per shape,
//! scaled by `size`, each type-checking cleanly and running to completion.

use std::fmt::Write as _;
use std::ops::RangeInclusive;

/// A corpus shape: what grows with `size`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, clap::ValueEnum)]
pub(crate) enum Shape {
    /// `size` independent functions.
    Functions,
    /// `size` modules, each importing only the previous one.
    ModulesPrev,
    /// `size` modules, each importing every earlier one.
    ModulesAll,
    /// A record alias `size` fields wide, updated by a fixed set of functions.
    Records,
    /// One body calling `size` distinct tools.
    Tools,
    /// A match on a `size`-wide tuple of `Bool`s.
    TupleMatch,
    /// A decision table: a match on a `size`-wide tuple of a 10-constructor enum.
    DecisionTable,
    /// One body that is a `size`-link chain of `let … in` and `;`, at most 120.
    Deep,
    /// `size` supervised actors, each driven through one round from `main`.
    Actors,
}

impl Shape {
    /// Every shape, in declaration order.
    #[cfg(test)]
    pub(crate) const ALL: [Self; 9] = [
        Self::Functions,
        Self::ModulesPrev,
        Self::ModulesAll,
        Self::Records,
        Self::Tools,
        Self::TupleMatch,
        Self::DecisionTable,
        Self::Deep,
        Self::Actors,
    ];

    /// The command-line name.
    pub(crate) fn name(self) -> &'static str {
        match self {
            Self::Functions => "functions",
            Self::ModulesPrev => "modules-prev",
            Self::ModulesAll => "modules-all",
            Self::Records => "records",
            Self::Tools => "tools",
            Self::TupleMatch => "tuple-match",
            Self::DecisionTable => "decision-table",
            Self::Deep => "deep",
            Self::Actors => "actors",
        }
    }

    /// The sizes the shape generates a valid program for.
    pub(crate) fn sizes(self) -> RangeInclusive<usize> {
        match self {
            // A 1-tuple is a parenthesized expression, not a tuple.
            Self::TupleMatch | Self::DecisionTable => 2..=usize::MAX,
            Self::Deep => 1..=DEEP_MAX,
            _ => 1..=usize::MAX,
        }
    }
}

/// Longest `deep` chain: a `let` link nests two parser levels, and the
/// parser caps nesting at 256.
pub(crate) const DEEP_MAX: usize = 120;

/// Functions per module in the `modules-*` shapes.
const MODULE_FUNCTIONS: usize = 20;

/// Functions updating the alias in the `records` shape.
const RECORD_FUNCTIONS: usize = 32;

/// Constructors of the `decision-table` enum.
const TABLE_CTORS: usize = 10;

/// Most calls per driver function in the `actors` shape; wider fleets
/// nest drivers so no `;` chain outgrows the parser's nesting cap.
const DRIVE_FANOUT: usize = 16;

/// One generated `.hird` file.
#[derive(Debug)]
pub(crate) struct SourceModule {
    /// `<stem>.hird`; the module name derives from the stem.
    pub(crate) file: String,
    /// The declared module name.
    pub(crate) name: String,
    /// The source text.
    pub(crate) source: String,
}

/// The `shape` program at `size` from `seed`, in module order; the same
/// arguments give the same bytes. `size` must be in [`Shape::sizes`].
pub(crate) fn generate(shape: Shape, size: usize, seed: u64) -> Vec<SourceModule> {
    assert!(
        shape.sizes().contains(&size),
        "size {size} is outside {}'s range",
        shape.name()
    );
    let banner = format!(
        "// Generated by hird-bench: {}, size {size}, seed {seed}.\n",
        shape.name()
    );
    let mut rng = Rng(seed);
    match shape {
        Shape::Functions => vec![functions(&banner, size, &mut rng)],
        Shape::ModulesPrev => modules(&banner, size, false, &mut rng),
        Shape::ModulesAll => modules(&banner, size, true, &mut rng),
        Shape::Records => vec![records(&banner, size, &mut rng)],
        Shape::Tools => vec![tools(&banner, size, &mut rng)],
        Shape::TupleMatch => vec![tuple_match(&banner, size, &mut rng)],
        Shape::DecisionTable => vec![decision_table(&banner, size, &mut rng)],
        Shape::Deep => vec![deep(&banner, size, &mut rng)],
        Shape::Actors => vec![actors(&banner, size, &mut rng)],
    }
}

/// `SplitMix64`: seedable, and stable across platforms and releases.
struct Rng(u64);

impl Rng {
    /// The next 64 bits.
    fn next_u64(&mut self) -> u64 {
        self.0 = self.0.wrapping_add(0x9e37_79b9_7f4a_7c15);
        let mut z = self.0;
        z = (z ^ (z >> 30)).wrapping_mul(0xbf58_476d_1ce4_e5b9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94d0_49bb_1331_11eb);
        z ^ (z >> 31)
    }

    /// A value in `0..n`, `n > 0`.
    fn below(&mut self, n: usize) -> usize {
        let n = u64::try_from(n).expect("usize fits in u64");
        usize::try_from(self.next_u64() % n).expect("a value below a usize fits in usize")
    }

    /// A value in `lo..=hi`.
    fn range(&mut self, lo: usize, hi: usize) -> usize {
        lo + self.below(hi - lo + 1)
    }

    /// A fair coin.
    fn coin(&mut self) -> bool {
        self.next_u64() & 1 == 1
    }

    /// `0..n` shuffled (Fisher–Yates).
    fn permutation(&mut self, n: usize) -> Vec<usize> {
        let mut out: Vec<usize> = (0..n).collect();
        for i in (1..n).rev() {
            out.swap(i, self.below(i + 1));
        }
        out
    }
}

/// A single-module corpus file: `<stem>.hird` declaring `name`.
fn single(stem: &str, name: &str, source: String) -> SourceModule {
    SourceModule {
        file: format!("{stem}.hird"),
        name: name.to_owned(),
        source,
    }
}

/// `banner`, then `module <name>`.
fn start(banner: &str, name: &str) -> String {
    format!("{banner}\nmodule {name}\n\n")
}

/// `functions`: `f1` … `f<size>`, no calls between them; `main` calls the
/// first and the last.
fn functions(banner: &str, size: usize, rng: &mut Rng) -> SourceModule {
    let mut src = start(banner, "Functions");
    src.push_str("type Shape = Circle(Int) | Square(Int) | Empty\n\n");
    // Whether each function takes a `Shape` second, for `main`'s arguments.
    let mut takes_shape = Vec::with_capacity(size);
    for i in 1..=size {
        let (k, c) = (rng.range(2, 9), rng.range(1, 99));
        let template = rng.below(3);
        let _ = match template {
            0 => writeln!(
                src,
                "fn f{i}(x: Int, y: Int) → Int =\n  let a = x + y in\n  let b = a * {k} in\n  \
                 if b > {c} then a else b\n"
            ),
            1 => writeln!(
                src,
                "fn f{i}(x: Int, s: Shape) → Int =\n  match s {{\n    Circle(r) → x + r * {k},\n    \
                 Square(w) → if w > x then w - {c} else x,\n    Empty → x,\n  }}\n"
            ),
            _ => writeln!(src, "fn f{i}(x: Int, y: Int) → Int = (x - y) * {k} + {c}\n"),
        };
        takes_shape.push(template == 1);
    }
    let call = |i: usize| {
        let arg = if takes_shape[i - 1] { "Circle(2)" } else { "2" };
        format!("let _ = f{i}(1, {arg}) in\n  ")
    };
    let mut main = call(1);
    if size > 1 {
        main.push_str(&call(size));
    }
    let _ = writeln!(src, "fn main() → () =\n  {main}()");
    single("functions", "Functions", src)
}

/// `modules-prev` / `modules-all`: modules `M001` … each defining `g1` …
/// `g20`; past the first, each `g` calls a `g` of an imported module, and
/// the last module's `main` calls its `g1`.
fn modules(banner: &str, size: usize, import_all: bool, rng: &mut Rng) -> Vec<SourceModule> {
    let width = size.to_string().len().max(3);
    let name = |i: usize| format!("M{i:0width$}");
    let mut out = Vec::with_capacity(size);
    for i in 1..=size {
        let mut src = start(banner, &name(i));
        let imports: Vec<usize> = match i {
            1 => Vec::new(),
            _ if import_all => (1..i).collect(),
            _ => vec![i - 1],
        };
        for &j in &imports {
            let _ = writeln!(src, "use {}", name(j));
        }
        if !imports.is_empty() {
            src.push('\n');
        }
        let _ = writeln!(src, "pub type Shape{i} = Circle{i}(Int) | Square{i}(Int)\n");
        for g in 1..=MODULE_FUNCTIONS {
            let c = rng.range(1, 99);
            if imports.is_empty() {
                let _ = writeln!(src, "pub fn g{g}(x: Int) → Int = x + {c}\n");
            } else {
                let target = name(imports[rng.below(imports.len())]);
                let h = rng.range(1, MODULE_FUNCTIONS);
                let _ = writeln!(src, "pub fn g{g}(x: Int) → Int = {target}.g{h}(x) + {c}\n");
            }
        }
        let k = rng.range(2, 9);
        let _ = writeln!(
            src,
            "pub fn area{i}(s: Shape{i}) → Int =\n  match s {{\n    Circle{i}(r) → r * r,\n    \
             Square{i}(w) → w * {k},\n  }}"
        );
        if i == size {
            let _ = writeln!(
                src,
                "\nfn main() → () =\n  let _ = g1(1) in\n  let _ = area{i}(Circle{i}(2)) in\n  ()"
            );
        }
        out.push(SourceModule {
            file: format!("m{i:0width$}.hird"),
            name: name(i),
            source: src,
        });
    }
    out
}

/// `records`: `type alias Wide` with fields `f1` … `f<size>`, its full
/// literal in `mk`, and 32 functions each updating it twice.
fn records(banner: &str, size: usize, rng: &mut Rng) -> SourceModule {
    let mut src = start(banner, "Records");
    let fields: Vec<String> = (1..=size).map(|f| format!("f{f}: Int")).collect();
    let _ = writeln!(src, "type alias Wide = {{ {} }}\n", fields.join(", "));
    let inits: Vec<String> = (1..=size)
        .map(|f| format!("f{f}: x + {}", rng.range(0, 99)))
        .collect();
    let _ = writeln!(src, "fn mk(x: Int) → Wide = {{ {} }}\n", inits.join(", "));
    for g in 1..=RECORD_FUNCTIONS {
        let (a, b, c) = (rng.range(1, size), rng.range(1, size), rng.range(1, size));
        let k = rng.range(1, 9);
        let _ = writeln!(
            src,
            "fn g{g}(r: Wide) → Wide =\n  let s = {{ f{a}: r.f{b} + {k}, ..r }} in\n  \
             {{ f{c}: s.f{a} * 2, ..s }}\n"
        );
    }
    let _ = writeln!(src, "fn total(r: Wide) → Int = r.f1 + r.f{size}\n");
    src.push_str("fn main() → () =\n  let r = g1(mk(1)) in\n  let _ = total(r) in\n  ()\n");
    single("records", "Records", src)
}

/// `tools`: `Tool1` … `Tool<size>`, one body calling each once (row and
/// calls in seeded orders), handled in `run_all`.
fn tools(banner: &str, size: usize, rng: &mut Rng) -> SourceModule {
    let mut src = start(banner, "Tools");
    for t in 1..=size {
        let _ = writeln!(src, "tool Tool{t} : Int → Int");
    }
    let row: Vec<String> = rng
        .permutation(size)
        .into_iter()
        .map(|t| format!("Tool<Tool{}>", t + 1))
        .collect();
    let calls: Vec<String> = rng
        .permutation(size)
        .into_iter()
        .map(|t| format!("tool{}(x)", t + 1))
        .collect();
    let _ = writeln!(
        src,
        "\nfn call_all(x: Int) → Int ! {{{}}} =\n  {}\n",
        row.join(", "),
        calls.join("\n  + ")
    );
    src.push_str("fn echo(x: Int) → Int = x\n\nfn run_all() → Int =\n  handle {\n");
    for t in 1..=size {
        let _ = writeln!(src, "    Tool<Tool{t}> → echo,");
    }
    src.push_str("  } in call_all(1)\n\nfn main() → () = let _ = run_all() in ()\n");
    single("tools", "Tools", src)
}

/// `tuple-match`: one seeded row over `size` `Bool`s, then `_`.
fn tuple_match(banner: &str, size: usize, rng: &mut Rng) -> SourceModule {
    let mut src = start(banner, "TupleMatch");
    let params: Vec<String> = (1..=size).map(|i| format!("a{i}: Bool")).collect();
    let scrutinee: Vec<String> = (1..=size).map(|i| format!("a{i}")).collect();
    let row: Vec<&str> = (0..size)
        .map(|_| if rng.coin() { "True" } else { "False" })
        .collect();
    let _ = writeln!(
        src,
        "fn classify({}) → Int =\n  match ({}) {{\n    ({}) → 1,\n    _ → 0,\n  }}\n",
        params.join(", "),
        scrutinee.join(", "),
        row.join(", ")
    );
    let _ = writeln!(
        src,
        "fn main() → () = let _ = classify({}) in ()",
        row.join(", ")
    );
    single("tuple_match", "TupleMatch", src)
}

/// `decision-table`: 10 rows over a `size`-wide tuple of `Level`, each
/// column a seeded permutation of the constructors, then `_`.
fn decision_table(banner: &str, size: usize, rng: &mut Rng) -> SourceModule {
    let mut src = start(banner, "DecisionTable");
    let ctors: Vec<String> = (1..=TABLE_CTORS).map(|c| format!("L{c}")).collect();
    let _ = writeln!(src, "type Level = {}\n", ctors.join(" | "));
    let params: Vec<String> = (1..=size).map(|i| format!("a{i}: Level")).collect();
    let scrutinee: Vec<String> = (1..=size).map(|i| format!("a{i}")).collect();
    let _ = writeln!(
        src,
        "fn decide({}) → Int =\n  match ({}) {{",
        params.join(", "),
        scrutinee.join(", ")
    );
    // Column 0 is a permutation, so the rows are pairwise distinct.
    let columns: Vec<Vec<usize>> = (0..size).map(|_| rng.permutation(TABLE_CTORS)).collect();
    for row in 0..TABLE_CTORS {
        let cells: Vec<&str> = columns.iter().map(|c| ctors[c[row]].as_str()).collect();
        let _ = writeln!(src, "    ({}) → {},", cells.join(", "), row + 1);
    }
    let args = vec!["L1"; size].join(", ");
    let _ = writeln!(
        src,
        "    _ → 0,\n  }}\n\nfn main() → () = let _ = decide({args}) in ()"
    );
    single("decision_table", "DecisionTable", src)
}

/// `deep`: `chain`, whose body is `size` seeded links of `let v = … in`
/// or `note(…);`.
fn deep(banner: &str, size: usize, rng: &mut Rng) -> SourceModule {
    let mut src = start(banner, "Deep");
    src.push_str("fn note(x: Int) → () = ()\n\nfn chain(x: Int) → Int =\n");
    let mut last = String::from("x");
    for i in 1..=size {
        let c = rng.range(1, 99);
        let op = if rng.coin() { '+' } else { '-' };
        if rng.coin() {
            let _ = writeln!(src, "  let v{i} = {last} {op} {c} in");
            last = format!("v{i}");
        } else {
            let _ = writeln!(src, "  note({last} {op} {c});");
        }
    }
    let _ = writeln!(src, "  {last}\n\nfn main() → () = let _ = chain(1) in ()");
    single("deep", "Deep", src)
}

/// `actors`: `Worker1` … `Worker<size>` under one supervisor, each bumped
/// and read back by a driver; drivers nest [`DRIVE_FANOUT`] wide.
fn actors(banner: &str, size: usize, rng: &mut Rng) -> SourceModule {
    let mut src = start(banner, "Actors");
    src.push_str(
        "tool Stamp : Int → Int\n\ntype alias Tally = { count: Int, stamps: Int }\n\n\
         fn stamp_impl(x: Int) → Int = x\n\n",
    );
    let mut children = String::new();
    let mut drivers = String::new();
    for i in 1..=size {
        let (start, bump) = (rng.range(0, 9), rng.range(1, 9));
        let restart = if rng.coin() { "permanent" } else { "transient" };
        let _ = writeln!(
            src,
            "actor Worker{i} {{\n  state: Tally,\n\n  \
             message: Worker{i}Msg =\n    | Bump{i}(Int)\n    | Read{i}(ReplyTo<Int>),\n\n  \
             init: fn(start: Int) ! {{}} = {{ count: start, stamps: 0 }},\n\n  \
             handle Bump{i}(by), st ! {{Tool<Stamp>}} =\n    let s = stamp(by) in\n    \
             Continue({{ count: st.count + by, stamps: st.stamps + s }}),\n\n  \
             handle Read{i}(reply_to), st ! {{Send<Int>}} =\n    reply(reply_to, st.count);\n    \
             Continue(st),\n}} ! {{Tool<Stamp>, Send<Int>}}\n"
        );
        let _ = writeln!(
            children,
            "    {{ id: worker{i}, actor: Worker{i}, start_args: {start}, restart: {restart} }},"
        );
        let _ = writeln!(
            drivers,
            "fn drive{i}() → () ! {{Send<Worker{i}Msg>, Await<Int>}} =\n  \
             let w = child(Fleet, worker{i}) in\n  send(w, Bump{i}({bump}));\n  \
             let n = request(w, Read{i}) in\n  \
             if n == {} then () else crash!(\"worker{i} lost a bump\")\n",
            start + bump
        );
    }
    let _ = writeln!(
        src,
        "supervisor Fleet {{\n  strategy: one_for_one,\n  intensity: 5,\n  period: 60,\n  \
         children: [\n{children}  ]\n}}\n"
    );
    src.push_str(&drivers);

    // Each level groups the previous one's calls, carrying the workers
    // each call reaches so its row can be declared.
    let mut level: Vec<(String, Vec<usize>)> =
        (1..=size).map(|i| (format!("drive{i}"), vec![i])).collect();
    let mut depth = 0;
    while level.len() > DRIVE_FANOUT {
        depth += 1;
        let mut next = Vec::new();
        for (g, chunk) in level.chunks(DRIVE_FANOUT).enumerate() {
            let name = format!("drive_{depth}_{}", g + 1);
            let workers: Vec<usize> = chunk.iter().flat_map(|(_, w)| w.iter().copied()).collect();
            let _ = writeln!(
                src,
                "fn {name}() → () ! {{{}}} =\n  {}\n",
                fleet_row(&workers),
                calls(chunk)
            );
            next.push((name, workers));
        }
        level = next;
    }
    let all: Vec<usize> = (1..=size).collect();
    let row = fleet_row(&all);
    let _ = writeln!(
        src,
        "fn run_fleet() → () ! {{Supervise, {row}}} =\n  supervise(Fleet);\n  {}\n",
        calls(&level)
    );
    let _ = writeln!(
        src,
        "fn main() → () ! {{Install, Supervise, {row}}} =\n  \
         install {{ Tool<Stamp> → stamp_impl }} in run_fleet()"
    );
    single("actors", "Actors", src)
}

/// `Send<Worker<i>Msg>` for each of `workers`, then `Await<Int>`.
fn fleet_row(workers: &[usize]) -> String {
    let mut row: Vec<String> = workers
        .iter()
        .map(|i| format!("Send<Worker{i}Msg>"))
        .collect();
    row.push("Await<Int>".to_owned());
    row.join(", ")
}

/// `a();\n  b(); …` over the named driver calls.
fn calls(level: &[(String, Vec<usize>)]) -> String {
    level
        .iter()
        .map(|(name, _)| format!("{name}()"))
        .collect::<Vec<_>>()
        .join(";\n  ")
}

#[cfg(test)]
mod tests {
    use hird_ast::{AstNode, SourceFile};
    use hird_check::ModuleName;

    use super::{DEEP_MAX, Shape, SourceModule, generate};

    /// Parse and check diagnostics of every severity, rendered one per line.
    fn diagnostics(modules: &[SourceModule]) -> Vec<String> {
        let mut out = Vec::new();
        let mut program = Vec::new();
        for (id, module) in modules.iter().enumerate() {
            let parsed = hird_parse::parse(&module.source, u32::try_from(id).unwrap());
            for d in parsed.diagnostics() {
                out.push(format!("{}: {:?} {}", module.file, d.code, d.message));
            }
            let file = SourceFile::cast(parsed.syntax().clone()).unwrap();
            program.push((ModuleName::new(module.name.clone()), file));
        }
        if !out.is_empty() {
            return out;
        }
        let checked = hird_check::check_program(&program);
        for module in checked.modules.values() {
            for d in &module.diagnostics {
                out.push(format!("{:?} {:?}: {}", d.severity, d.code, d.message));
            }
        }
        out
    }

    /// The sizes each shape is checked at.
    fn sizes(shape: Shape) -> &'static [usize] {
        match shape {
            // Exhaustiveness checking is exponential in tuple width, so these
            // stay narrow enough to check in milliseconds.
            Shape::TupleMatch => &[2, 3, 8, 12],
            Shape::DecisionTable => &[2, 3, 4],
            Shape::Deep => &[1, 2, 7, DEEP_MAX],
            // One level of driver nesting past 16 actors, two past 256.
            Shape::Actors => &[1, 2, 17, 300],
            _ => &[1, 2, 7, 40],
        }
    }

    #[test]
    fn every_shape_checks_cleanly() {
        for shape in Shape::ALL {
            for &size in sizes(shape) {
                for seed in [0, 1, 0xdead_beef] {
                    let diags = diagnostics(&generate(shape, size, seed));
                    assert!(
                        diags.is_empty(),
                        "{} at size {size}, seed {seed}:\n{}",
                        shape.name(),
                        diags.join("\n")
                    );
                }
            }
        }
    }

    #[test]
    fn same_seed_same_bytes() {
        for shape in Shape::ALL {
            let size = *shape.sizes().start() + 7;
            let render = |seed| {
                generate(shape, size, seed)
                    .into_iter()
                    .map(|m| format!("{}\n{}", m.file, m.source))
                    .collect::<String>()
            };
            assert_eq!(
                render(42),
                render(42),
                "{} is not deterministic",
                shape.name()
            );
            assert_ne!(render(42), render(43), "{} ignores its seed", shape.name());
        }
    }

    #[test]
    fn modules_import_as_named() {
        let prev = generate(Shape::ModulesPrev, 4, 0);
        let all = generate(Shape::ModulesAll, 4, 0);
        let uses = |m: &SourceModule| m.source.lines().filter(|l| l.starts_with("use ")).count();
        assert_eq!(prev.iter().map(uses).collect::<Vec<_>>(), [0, 1, 1, 1]);
        assert_eq!(all.iter().map(uses).collect::<Vec<_>>(), [0, 1, 2, 3]);
        assert_eq!(prev[3].file, "m004.hird");
        assert_eq!(prev[3].name, "M004");
    }

    #[test]
    fn deep_max_parses_as_all_lets() {
        // The worst case for nesting: every link a `let`.
        let mut chain = String::from("fn chain(x: Int) → Int =\n  let v0 = x in\n");
        for i in 1..=DEEP_MAX {
            chain.push_str(&format!("  let v{i} = v{} - 99 in\n", i - 1));
        }
        chain.push_str(&format!("  v{DEEP_MAX}\n"));
        let parsed = hird_parse::parse(&chain, 0);
        assert!(parsed.is_ok(), "{:?}", parsed.diagnostics());
    }
}
