[package]
name = "hird-parse"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Hirð parser and CST construction"
publish = false

[dependencies]
cstree.workspace = true
hird-lex.workspace = true

[dev-dependencies]
cstree.workspace = true

[lints]
workspace = true
