[package]
name = "hird-codegen"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Hirð Erlang source emission from IR"
publish = false

[dependencies]
hird-ir.workspace = true
hird-types.workspace = true

[dev-dependencies]
hird-ast.workspace = true
hird-check.workspace = true
hird-parse.workspace = true
insta = "1"

[lints]
workspace = true
