[package]
name = "hird-cli"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Hirð compiler CLI"
publish = false

[[bin]]
name = "hird"
path = "src/main.rs"

[dependencies]
hird-ast.workspace = true
hird-check.workspace = true
hird-codegen.workspace = true
hird-ir.workspace = true
hird-parse = { features = ["std"], workspace = true }
hird-types.workspace = true

clap = { features = ["derive"], version = "4" }
miette = { default-features = false, features = ["fancy-no-syscall"], version = "7" }
serde_json = "1"

[lints]
workspace = true
